wandb_version: 1

noise_type:
  desc: null
  value: normal
noise_mean:
  desc: null
  value: 0.0
noise_std:
  desc: null
  value: 1.0
noise_min:
  desc: null
  value: -1.0
noise_max:
  desc: null
  value: 1.0
noise_lambda:
  desc: null
  value: 1.0
noise_alpha:
  desc: null
  value: 2.0
noise_beta:
  desc: null
  value: 1.0
hidden_layers_d:
  desc: null
  value: 1
hidden_layers_g:
  desc: null
  value: 2
latent_size:
  desc: null
  value: 64
hidden_size:
  desc: null
  value: 256
image_size:
  desc: null
  value: 784
img_dim:
  desc: null
  value: 28
batch_size:
  desc: null
  value: 200
learning_rate:
  desc: null
  value: 0.0002
num_epochs:
  desc: null
  value: 200
reduction_factor:
  desc: null
  value: 1.0
dataset:
  desc: null
  value: MNIST
log_wandb:
  desc: null
  value: true
project_wandb:
  desc: null
  value: gan-noise-investigation-test
run_on_notebook:
  desc: null
  value: true
photonic_layers:
  desc: null
  value: 2
photonic_modes:
  desc: null
  value: 4
_wandb:
  desc: null
  value:
    python_version: 3.12.4
    cli_version: 0.17.8
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1738155994
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.12.4
      5: 0.17.8
      8:
      - 1
      - 5
      13: linux-x86_64
